// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLoggerIF creates a new instance of MockLoggerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerIF {
	mock := &MockLoggerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggerIF is an autogenerated mock type for the LoggerIF type
type MockLoggerIF struct {
	mock.Mock
}

type MockLoggerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerIF) EXPECT() *MockLoggerIF_Expecter {
	return &MockLoggerIF_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Debug(ctx context.Context, msg string) {
	_mock.Called(ctx, msg)
	return
}

// MockLoggerIF_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLoggerIF_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
func (_e *MockLoggerIF_Expecter) Debug(ctx interface{}, msg interface{}) *MockLoggerIF_Debug_Call {
	return &MockLoggerIF_Debug_Call{Call: _e.mock.On("Debug", ctx, msg)}
}

func (_c *MockLoggerIF_Debug_Call) Run(run func(ctx context.Context, msg string)) *MockLoggerIF_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Debug_Call) Return() *MockLoggerIF_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Debug_Call) RunAndReturn(run func(ctx context.Context, msg string)) *MockLoggerIF_Debug_Call {
	_c.Run(run)
	return _c
}

// Debugf provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Debugf(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLoggerIF_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type MockLoggerIF_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLoggerIF_Expecter) Debugf(ctx interface{}, format interface{}, args ...interface{}) *MockLoggerIF_Debugf_Call {
	return &MockLoggerIF_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLoggerIF_Debugf_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Debugf_Call) Return() *MockLoggerIF_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Debugf_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Debugf_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Error(ctx context.Context, msg string) {
	_mock.Called(ctx, msg)
	return
}

// MockLoggerIF_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLoggerIF_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
func (_e *MockLoggerIF_Expecter) Error(ctx interface{}, msg interface{}) *MockLoggerIF_Error_Call {
	return &MockLoggerIF_Error_Call{Call: _e.mock.On("Error", ctx, msg)}
}

func (_c *MockLoggerIF_Error_Call) Run(run func(ctx context.Context, msg string)) *MockLoggerIF_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Error_Call) Return() *MockLoggerIF_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Error_Call) RunAndReturn(run func(ctx context.Context, msg string)) *MockLoggerIF_Error_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Errorf(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLoggerIF_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type MockLoggerIF_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLoggerIF_Expecter) Errorf(ctx interface{}, format interface{}, args ...interface{}) *MockLoggerIF_Errorf_Call {
	return &MockLoggerIF_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLoggerIF_Errorf_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Errorf_Call) Return() *MockLoggerIF_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Errorf_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Errorf_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Fatal(ctx context.Context, msg string) {
	_mock.Called(ctx, msg)
	return
}

// MockLoggerIF_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockLoggerIF_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
func (_e *MockLoggerIF_Expecter) Fatal(ctx interface{}, msg interface{}) *MockLoggerIF_Fatal_Call {
	return &MockLoggerIF_Fatal_Call{Call: _e.mock.On("Fatal", ctx, msg)}
}

func (_c *MockLoggerIF_Fatal_Call) Run(run func(ctx context.Context, msg string)) *MockLoggerIF_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Fatal_Call) Return() *MockLoggerIF_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Fatal_Call) RunAndReturn(run func(ctx context.Context, msg string)) *MockLoggerIF_Fatal_Call {
	_c.Run(run)
	return _c
}

// Fatalf provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Fatalf(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLoggerIF_Fatalf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatalf'
type MockLoggerIF_Fatalf_Call struct {
	*mock.Call
}

// Fatalf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLoggerIF_Expecter) Fatalf(ctx interface{}, format interface{}, args ...interface{}) *MockLoggerIF_Fatalf_Call {
	return &MockLoggerIF_Fatalf_Call{Call: _e.mock.On("Fatalf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLoggerIF_Fatalf_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Fatalf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Fatalf_Call) Return() *MockLoggerIF_Fatalf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Fatalf_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Fatalf_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Info(ctx context.Context, msg string) {
	_mock.Called(ctx, msg)
	return
}

// MockLoggerIF_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLoggerIF_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
func (_e *MockLoggerIF_Expecter) Info(ctx interface{}, msg interface{}) *MockLoggerIF_Info_Call {
	return &MockLoggerIF_Info_Call{Call: _e.mock.On("Info", ctx, msg)}
}

func (_c *MockLoggerIF_Info_Call) Run(run func(ctx context.Context, msg string)) *MockLoggerIF_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Info_Call) Return() *MockLoggerIF_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Info_Call) RunAndReturn(run func(ctx context.Context, msg string)) *MockLoggerIF_Info_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Infof(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLoggerIF_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockLoggerIF_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLoggerIF_Expecter) Infof(ctx interface{}, format interface{}, args ...interface{}) *MockLoggerIF_Infof_Call {
	return &MockLoggerIF_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLoggerIF_Infof_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Infof_Call) Return() *MockLoggerIF_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Infof_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Infof_Call {
	_c.Run(run)
	return _c
}

// Panic provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Panic(ctx context.Context, msg string) {
	_mock.Called(ctx, msg)
	return
}

// MockLoggerIF_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type MockLoggerIF_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
func (_e *MockLoggerIF_Expecter) Panic(ctx interface{}, msg interface{}) *MockLoggerIF_Panic_Call {
	return &MockLoggerIF_Panic_Call{Call: _e.mock.On("Panic", ctx, msg)}
}

func (_c *MockLoggerIF_Panic_Call) Run(run func(ctx context.Context, msg string)) *MockLoggerIF_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Panic_Call) Return() *MockLoggerIF_Panic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Panic_Call) RunAndReturn(run func(ctx context.Context, msg string)) *MockLoggerIF_Panic_Call {
	_c.Run(run)
	return _c
}

// Panicf provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Panicf(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLoggerIF_Panicf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panicf'
type MockLoggerIF_Panicf_Call struct {
	*mock.Call
}

// Panicf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLoggerIF_Expecter) Panicf(ctx interface{}, format interface{}, args ...interface{}) *MockLoggerIF_Panicf_Call {
	return &MockLoggerIF_Panicf_Call{Call: _e.mock.On("Panicf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLoggerIF_Panicf_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Panicf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Panicf_Call) Return() *MockLoggerIF_Panicf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Panicf_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Panicf_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Warn(ctx context.Context, msg string) {
	_mock.Called(ctx, msg)
	return
}

// MockLoggerIF_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLoggerIF_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
func (_e *MockLoggerIF_Expecter) Warn(ctx interface{}, msg interface{}) *MockLoggerIF_Warn_Call {
	return &MockLoggerIF_Warn_Call{Call: _e.mock.On("Warn", ctx, msg)}
}

func (_c *MockLoggerIF_Warn_Call) Run(run func(ctx context.Context, msg string)) *MockLoggerIF_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Warn_Call) Return() *MockLoggerIF_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Warn_Call) RunAndReturn(run func(ctx context.Context, msg string)) *MockLoggerIF_Warn_Call {
	_c.Run(run)
	return _c
}

// Warnf provides a mock function for the type MockLoggerIF
func (_mock *MockLoggerIF) Warnf(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLoggerIF_Warnf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnf'
type MockLoggerIF_Warnf_Call struct {
	*mock.Call
}

// Warnf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLoggerIF_Expecter) Warnf(ctx interface{}, format interface{}, args ...interface{}) *MockLoggerIF_Warnf_Call {
	return &MockLoggerIF_Warnf_Call{Call: _e.mock.On("Warnf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLoggerIF_Warnf_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Warnf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLoggerIF_Warnf_Call) Return() *MockLoggerIF_Warnf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerIF_Warnf_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLoggerIF_Warnf_Call {
	_c.Run(run)
	return _c
}
