// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/MXLange/go-model/internal/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryIF creates a new instance of MockRepositoryIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryIF {
	mock := &MockRepositoryIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryIF is an autogenerated mock type for the repositoryIF type
type MockRepositoryIF struct {
	mock.Mock
}

type MockRepositoryIF_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryIF) EXPECT() *MockRepositoryIF_Expecter {
	return &MockRepositoryIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepositoryIF
func (_mock *MockRepositoryIF) Create(ctx context.Context, name string) (int, *errors.AppError) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, *errors.AppError)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *errors.AppError); ok {
		r1 = returnFunc(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockRepositoryIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepositoryIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRepositoryIF_Expecter) Create(ctx interface{}, name interface{}) *MockRepositoryIF_Create_Call {
	return &MockRepositoryIF_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *MockRepositoryIF_Create_Call) Run(run func(ctx context.Context, name string)) *MockRepositoryIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryIF_Create_Call) Return(n int, appError *errors.AppError) *MockRepositoryIF_Create_Call {
	_c.Call.Return(n, appError)
	return _c
}

func (_c *MockRepositoryIF_Create_Call) RunAndReturn(run func(ctx context.Context, name string) (int, *errors.AppError)) *MockRepositoryIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockRepositoryIF
func (_mock *MockRepositoryIF) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryIF_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRepositoryIF_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryIF_Expecter) Ping(ctx interface{}) *MockRepositoryIF_Ping_Call {
	return &MockRepositoryIF_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockRepositoryIF_Ping_Call) Run(run func(ctx context.Context)) *MockRepositoryIF_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryIF_Ping_Call) Return(err error) *MockRepositoryIF_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryIF_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepositoryIF_Ping_Call {
	_c.Call.Return(run)
	return _c
}
