// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/MXLange/go-model/internal/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServicesIF creates a new instance of MockServicesIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicesIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicesIF {
	mock := &MockServicesIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServicesIF is an autogenerated mock type for the servicesIF type
type MockServicesIF struct {
	mock.Mock
}

type MockServicesIF_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicesIF) EXPECT() *MockServicesIF_Expecter {
	return &MockServicesIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockServicesIF
func (_mock *MockServicesIF) Create(ctx context.Context, name string) (int, *errors.AppError) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, *errors.AppError)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *errors.AppError); ok {
		r1 = returnFunc(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockServicesIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServicesIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockServicesIF_Expecter) Create(ctx interface{}, name interface{}) *MockServicesIF_Create_Call {
	return &MockServicesIF_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *MockServicesIF_Create_Call) Run(run func(ctx context.Context, name string)) *MockServicesIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServicesIF_Create_Call) Return(n int, appError *errors.AppError) *MockServicesIF_Create_Call {
	_c.Call.Return(n, appError)
	return _c
}

func (_c *MockServicesIF_Create_Call) RunAndReturn(run func(ctx context.Context, name string) (int, *errors.AppError)) *MockServicesIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockServicesIF
func (_mock *MockServicesIF) Health(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServicesIF_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockServicesIF_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServicesIF_Expecter) Health(ctx interface{}) *MockServicesIF_Health_Call {
	return &MockServicesIF_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *MockServicesIF_Health_Call) Run(run func(ctx context.Context)) *MockServicesIF_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServicesIF_Health_Call) Return(err error) *MockServicesIF_Health_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServicesIF_Health_Call) RunAndReturn(run func(ctx context.Context) error) *MockServicesIF_Health_Call {
	_c.Call.Return(run)
	return _c
}
